# Site settings
title: My Website
email: 
description: 
paginate: 2
paginate_path: '/page/:num/'

# Build settings
markdown: kramdown
permalink: pretty
gems:
- jekyll-paginate
include: ['_pages']
exclude: ['node_modules', 'assets/sass', 'assets/pug', 'gulpfile.js', 'package.json', 'README.md', 'CNAME']